package me.druid.v1.forms;

public enum SkinId {
    SKIN_GRIZZLY,
    SKIN_POLAR_BEAR,
    SKIN_CAVE_REX,

    SKIN_TIGER_SABERTOOTH,
    SKIN_PANTHER,
    SKIN_CAVE_RAPTOR,
    SKIN_HYENA,
    SKIN_SNOW_LEOPARD,
    SKIN_WOLF,

    SKIN_SHARK,
    SKIN_PIRANHA,
    SKIN_SNAPJAW,

    SKIN_ANTELOPE,
    SKIN_DEER_STAG,
    SKIN_HORSE,
    SKIN_SKELETAL_HORSE,
    SKIN_CAMEL,

    SKIN_HAWK,
    SKIN_CROW,
    SKIN_BAT_SNOW_BAT,
    SKIN_DUCK,
    SKIN_OWL,
    SKIN_PARROT,
    SKIN_PIGEON,
    SKIN_PTERODACTYL,
    SKIN_FIRE_DRAGON,

    SKIN_RABBIT,
    SKIN_FROG,
    SKIN_CAT,
    SKIN_FOX,
    SKIN_SPIDER,

    SKIN_RAM,
    SKIN_GOAT,
    SKIN_MOOSE,
    SKIN_WARTHOG,
    SKIN_BISON,
    SKIN_TRILODON,

    SKIN_EEL,
    SKIN_BLUEGILL,
    SKIN_CLOWNFISH,
    SKIN_PIKE,
    SKIN_RAINBOW_TROUT,
    SKIN_TANG,
    SKIN_FROSTGILL
}
